### ISSUE TITLE
(🎁) Preserve requirement type (`^`/`~` caret / tilde)

### ISSUE THREAD

**Issue by KotlinIsland** [mousabaker/poetry-plugin-up#13]
I imagine a common workflow would be people running `poetry update`/`poetry up` occasional and `poetry up --latest` on a more infrequent basis. In this case and where a dependency is specified with a tilde (perhaps the dependency does not follow semver), I think it would be preferable that the `up`ed (with `--latest`) specifier retains the original requirement marker.

# Proposed
```toml
[tool.poetry.dependencies]
pendulum = "~2.0"
```
```
👉 poetry up --latest
```
```toml
[tool.poetry.dependencies]
pendulum = "~2.1.2"
```
