### ISSUE TITLE
(🎁) Don't up zero based versions

### ISSUE THREAD

**Issue by KotlinIsland** [mousabaker/poetry-plugin-up#25]
```toml
[tool.poetry.group.dev.dependencies]
ruff = "^0.0"
```
After `poetry up`:
```toml
[tool.poetry.group.dev.dependencies]
ruff = "^0.0.277"
```

This changes the semantics: `0.0` means ">=0.0.0 <0.1.0", `0.0.277` means ">=0.0.277 <0.0.278".

# Workaround
Use tilde, while not intended for the same use case as a zero caret, it might work.
```toml
[tool.poetry.group.dev.dependencies]
ruff = "~0.0.277"
```
