### ISSUE TITLE
'PyProjectTOML' object has no attribute 'file'

### ISSUE THREAD

**Issue by riton** [mousabaker/poetry-plugin-up#28]
## Description

On a fresh sample project with `pyproject.toml` dependencies such as:

```toml
[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
poetry-dynamic-versioning = "^1.0.0"
black = "^23.7.0"
pylint = "^2.17.5"
pyright = "^1.1.323"
tox = "^4.9.0"
poethepoet = "^0.16.5"
pytest-cov = "^4.1.0"
isort = "^5.12.0"
```

I get an error when I try to update the `dev` dependencies:

```
❯ poetry up --only dev

'PyProjectTOML' object has no attribute 'file'
```

[full debug trace.log](https://github.com/MousaZeidBaker/poetry-plugin-up/files/12376498/trace.log)

## Software versions

<details>

### Poetry

```
❯ poetry --version
Poetry (version 1.5.1)
```

It is installed with `pipx` with `Python 3.11.3`

### Poetry up

I'm using the latest version installed with `pipx inject poetry poetry-plugin-up`

### Poetry plugins

```
❯ poetry self show plugins

  • poetry-plugin-up (0.3.0) Poetry plugin that updates dependencies and bumps their versions in pyproject.toml file
      1 application plugin

      Dependencies
        - poetry (>=1.2.0,<2.0.0)

  • poetry-dynamic-versioning (0.21.4) Plugin for Poetry to enable dynamic versioning based on VCS tags
      1 application plugin

      Dependencies
        - dunamai (>=1.16.0,<2.0.0)
        - jinja2 (>=2.11.1,<4)
        - poetry (>=1.2.0,<2.0.0)
        - tomlkit (>=0.4)

  • poetry-plugin-export (1.4.0) Poetry plugin to export the dependencies to various formats
      1 application plugin

      Dependencies
        - poetry (>=1.5.0,<2.0.0)
        - poetry-core (>=1.6.0,<2.0.0)
```

### O.S

```json
❯ puppet facts | jq .os
{
  "architecture": "amd64",
  "distro": {
    "codename": "jammy",
    "description": "Ubuntu 22.04.3 LTS",
    "id": "Ubuntu",
    "release": {
      "full": "22.04",
      "major": "22.04"
    }
  },
  "family": "Debian",
  "hardware": "x86_64",
  "name": "Ubuntu",
  "release": {
    "full": "22.04",
    "major": "22.04"
  },
  "selinux": {
    "enabled": false
  }
}
```

</details>
